spring:
  application:
    name: wasl

  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/wasl_db

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  servlet:
    multipart:
      max-file-size: 105MB
      max-request-size: 110MB

  data:
    web:
      pageable:
        one-indexed-parameters: true

  docker:
    compose:
      enabled: true
      file: docker-compose.db.yml

security:
  jwt:
    secret: "/7LHCo1fbM7W2tuxaFndwPddh9krWcGqPxCS92TYI/CYNoWwRHClMz4yuxCc3AJAb9HlS8wRmJSYNSD37OSYzw=="
    expires-in: 15m
  refresh:
    expires-in: 7d
    token-byte-length: 64

storage:
  location: "upload"

media:
  max-gif-size: 5MB
  max-image-size: 15MB
  max-video-size: 100MB

  allowed-types:
    # image
    - image/jpeg
    - image/png
    - image/gif
    - image/webp

    # video
    - video/mp4
    - video/webm
    - video/quicktime