spring:
  application:
    name: wasl
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/wasl_db
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  docker:
    compose:
      enabled: true

security:
  jwt:
    secret: "/7LHCo1fbM7W2tuxaFndwPddh9krWcGqPxCS92TYI/CYNoWwRHClMz4yuxCc3AJAb9HlS8wRmJSYNSD37OSYzw=="
    expiration_ms: 900000 # 15 minutes
  refresh:
    size: 64
    expiration_days: 7